config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"

  resources :users, only: [:new, :create]

  get "login", to: "session#new"
  post "login", to: "session#create"
  delete "logout", to: "session#destroy"
  post "messages", to: "messages#create"

  mount ActionCable.server, at: "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum:3, maximim: 15},
                uniqueness: {case_sensitive: false}
    has_many :messages            
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?,:current_user
    
   def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
          !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert]= "Please! Login to Perform This Action"
            redirect_to login_path
        end
    end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user, only: [:create, :index]

  def index
    @messages = Message.all
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save 
      ActionCable.server.broadcast 'chatroom_channel', message: @message.body
    else
      flash[:alert] = "message did not saved"
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: "message", locals: { message: message })
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :already_logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by username: params["sessions"]["username"]
    if @user && @user.authenticate(params["sessions"]["password"])
      flash[:success] = "Sucessfully Logged In"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Login failed!! check User Name and Password"
      render "new"
    end
  end

  def destroy
    # binding.pry
    session[:user_id] = nil
    flash[:notice] = "Logged Out Sucessfully"
    redirect_to login_path
  end

  private

  def already_logged_in_redirect
    if logged_in?
      flash[:alert] = "you are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
         @user = User.new(params.require(:user).permit(:username,:password))
         if @user.save
            flash[:notice] ="Signed Up Sucessfully"
            session[:user_id]=@user.id
            redirect_to root_path
         else
            render 'new'
         end
        
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Someting
</h4>
<div class="ui two column grid">
  <div class="twelve wide  column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui  feed">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: messages_path) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body%>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="four wide  column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical pointing menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content|%>
  <div class="ui <%= message_type %>  message transition ">
    <i class="close icon"></i>
      <div class="header">
        <%= message_content %>
      </div>
    </div>
  <% end %>

app/views/layouts/_nav.html.erb
<div class="ui inverted small menu">
  <div class="ui container">
    <a class="active item" href="/">
      Chat Room
    </a>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        <% if logged_in? %>
          <div id='current-user'><%= current_user.username.capitalize %></div>
        <% else %>
          Account
        <% end %>
        <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log Out', logout_path,method: :delete ,class:"item" %>
          <% else %>
            <%= link_to 'Login', login_path ,class:"item" %>
          <%end%>
          <%= link_to 'SignUp', new_user_path ,class:"item" %>
        </div>
      </div>
      <% if logged_in? %>
        <div class="item">
          <%= button_to 'SignOut', logout_path, method: :delete ,class:"ui green button" %>
        </div>
      <% else %>
        <div id='current-user'> <%= link_to 'SignUp', new_user_path ,class:"item" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render partial: "layouts/nav"%>
      </div>
    </div>
    <div class="ui container">
      <%= render partial: "layouts/messages"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/session/new.html.erb
 
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">

        <%= form_with scope: :sessions ,url: login_path  ,local: true do |f|%>
            <div class="field">
             <%= f.label :username %>
            <div class="ui left icon input">
                <i class="user icon"></i>
                <%= f.text_field :username ,placeholder: "enter user name"%>
            </div>
            </div>
            <div class="field">
             <%= f.label :password %>
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <%= f.text_field :password ,placeholder: "enter password",type:"password"%>
            </div>
            </div>            
            <%= f.submit("Log In" ,class:"ui orange submit button")%>
        <%end%>

      </div>
    </div>
    <div class="middle aligned column">
      <%= link_to 'Sign Up  ', login_path ,class:"ui big button"%>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.full_messages.any? %>
  <div class="ui message">
    <i class="close icon"></i>
    <% @user.errors.full_messages.each do |err|%>
      <p style="color:red"><%= err %></p>
    <%end%>
  </div>
<%end%>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <%= form_with model: @user ,local: true do |f|%>
          <div class="field">
            <%= f.label :username %>
            <div class="ui left icon input">
              <i class="user icon"></i>
              <%= f.text_field :username ,placeholder: "enter user name"%>
            </div>
          </div>
          <div class="field">
            <%= f.label :password %>
            <div class="ui left icon input">
              <i class="lock icon"></i>
              <%= f.text_field :password ,placeholder: "enter password",type:"password"%>
            </div>
          </div>
          <%= f.submit("Sign Up" ,class:"ui blue submit button")%>
        <%end%>
      </div>
    </div>
    <div class="middle aligned column">
      <%= link_to 'Login  ', login_path ,class:"ui big button"%>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>